name: 'File(s) Existence'

on:
  push:
    branches:
      - master
      - release/**
  pull_request:
    branches:
      - release/**

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check packages main files existence
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          # Comma separated string with paths to files and directories to check for existence.
          # Supports glob paterns (https://github.com/isaacs/node-glob).
          files: "packages/**/package.json, packages/**/README.md, packages/**/CHANGELOG.md, packages/**/LICENSE, packages/**/.gitignore"
          # Ignore if a file name has upper or lower cases.
          ignore_case: true
          # Indicates whether to follow symbolic links.
          follow_symbolic_links: true
          # Makes the Action fail on missing files.
          allow_failure: true

      - name: Packages main files exist
        # "files_exists" outputs true if the file(s) exists, otherwise false.
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists.
        run: echo All files exists.
